# Step 1:
FROM madima/flutterci:3.7.7 AS builder

WORKDIR /app
COPY frontend/mysheet /app

RUN flutter build web

# Step 2:
FROM nginx:1.21.1-alpine

COPY --from=builder /app/build/web /usr/share/nginx/html
breakingchange
