# Step 1:
FROM debian:latest AS builder

RUN apt-get update && apt-get install -y git curl unzip && apt-get clean

RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter
ENV PATH="/usr/local/flutter/bin:/usr/local/flutter/bin/cache/dart-sdk/bin:$PATH"

RUN flutter doctor -v
RUN flutter channel master
RUN flutter upgrade

WORKDIR /app
COPY frontend/mysheet /app

RUN flutter build web

# Step 2:
FROM nginx:1.21.1-alpine

COPY --from=builder /app/build/web /usr/share/nginx/html
